### ISSUE TITLE
Issue Formatting on Dedicated Servers

### ISSUE THREAD

**Issue by NighthowlerStudios** [noeppi-noeppi/MineMention#3]
Kaleidio's Battle Pack 3.4.6 constantly has formatting issues on the server console anytime somebody sends a chat message

 "←[0m<←[0m←[0mNubilicious←[0m> ←[0m←[0mk←[0m"
 
 constantly those four characters show up.  it's annoyingly spammy, what's going on here?

**Comment by noeppi-noeppi** [comment]
MineMention uses [ANSI Escape Codes](https://en.wikipedia.org/wiki/ANSI_escape_code) to print the message colored into the console. Apparently your console can't handle these.

**Comment by NighthowlerStudios** [comment]
The console is Windows Command Prompt, which DOES actually support ANSI codes, but only certain colours, and using ESC[0m results in it spitting it out rather than "just using default text"

**Comment by NighthowlerStudios** [comment]
see here for reference.  feature only available on Windows 10 1909 and up, currently using 21H1

https://ss64.com/nt/syntax-ansi.html

**Comment by NighthowlerStudios** [comment]
I suppose we should consider this a Java bug then since Java, if the ANSI gets accepted, tosses it out before printing to CMD.
